version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest-flake8
    versions:
    - 1.0.7
  - dependency-name: coveralls
    versions:
    - 3.0.0
