language: python

matrix:
  include:
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true
  - python: "nightly"
    dist: xenial
    sudo: true
install:
    - "pip install -r requirements-test.txt"
script:
    PYTHONPATH=. py.test --cov
after_success:
    coveralls
