language: python

matrix:
  include:
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "nightly"
    dist: xenial
  - name: "Python on Windows"
    os: windows
    language: shell
    before_install:
      - choco install python --version 3.8.0
      - python -V
      - python -m venv venv
      - venv/Scripts/activate.bat
      - python -m pip install --upgrade pip wheel
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
    - "pip install -r requirements-test.txt"
script:
    PYTHONPATH=. py.test -vv --cov
after_success:
    coveralls
