name: Python application

on: [push]

jobs:
  build:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9.0-alpha - 3.9.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        pip install pytest
        pytest --flake8 --cov aiomsg tests
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Upload coverage
      env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          # This will only work if we also send a "done" event after the
          # whole job is finished.
          # See: https://docs.coveralls.io/parallel-build-webhook
          #COVERALLS_PARALLEL: "true"
          CI_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      if: matrix.os == 'ubuntu-latest'
      run: |
        coveralls
